### ISSUE TITLE
Heroku Login error

### ISSUE THREAD

**Issue by Discharg** [CSUMB-SCD/cst438-project1#38]
If you try to log in on Heroku and it gives you a server error, try again multiple times. Current bug will not let you login or register successfully and it is inconsistent with the number of times you have to do it.

**Comment by NicoleHipolito** [comment]
Tkinter issue: Heroku doesn't support it.
Even though we aren't including it, it automatically used them. 
Solution: Grabbed third-party heroku build support that provided more libraries.
